=== SalvaFCF/just-another-blog/SoniaWebUtil/src/main/resources/sonia/jsf/access/accessConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://dev.sonia.de/schema/accessConfig"
            elementFormDefault="qualified" xmlns:tns="http://dev.sonia.de/schema/accessConfig">
    <xsd:element name="access-config">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="rule" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="description" minOccurs="0"/>
                            <xsd:element name="conditions" type="tns:condition" />
                            <xsd:element name="actions">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="redirect" minOccurs="0"/>
                                        <xsd:element name="forward" minOccurs="0"/>
                                        <xsd:element name="action" minOccurs="0" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="class"/>
                                                    <xsd:element name="init-param" minOccurs="0" maxOccurs="unbounded" type="tns:init-param"/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="last" minOccurs="0" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="condition">
        <xsd:sequence>
            <xsd:element name="and" minOccurs="0" maxOccurs="unbounded" type="tns:condition"/>
            <xsd:element name="or" minOccurs="0" maxOccurs="unbounded" type="tns:condition"/>
            <xsd:element name="not" minOccurs="0" maxOccurs="unbounded" type="tns:condition"/>
            <xsd:element name="isUser" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="isUserInRole" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="uriMatches" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="scheme" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="condition" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="class"/>
                        <xsd:element name="init-param" minOccurs="0" maxOccurs="unbounded" type="tns:init-param"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="loggedIn" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="init-param">
        <xsd:sequence>
            <xsd:element name="param-name"/>
            <xsd:element name="param-value"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== SalvaFCF/just-another-blog/SoniaBlog/web/WEB-INF/config/access.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : access.xml
    Created on : September 23, 2008, 1:41 PM
    Author     : sdorra
    Description:
        Purpose of the document follows.
-->
<access-config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://dev.sonia.de/schema/accessConfig'
   xsi:schemaLocation='http://dev.sonia.de/schema/accessConfig file:/Users/sdorra/Projects/libraries/SoniaWebUtil/src/sonia/jsf/access/accessConfig.xsd'>
    <rule>
        <description>if app installed</description>
        <conditions>
            <not>
                <ViewIdMatches>/install/.*</ViewIdMatches>
            </not>
            <not>
                <condition>
                    <class>sonia.blog.app.InstalledCondition</class>
                </condition>
            </not>
        </conditions>
        <actions>
            <jsf-navigation>install</jsf-navigation>
            <jsf-message>Die Anwendung muss erst installiert werden</jsf-message>
        </actions>
        <last />
    </rule>
    <rule>
        <conditions>
            <ViewIdMatches>/install/.*</ViewIdMatches>
            <condition>
                <class>sonia.blog.app.InstalledCondition</class>
            </condition>
        </conditions>
        <actions>
            <redirect>/</redirect>
        </actions>
    </rule>
    <!--<rule>
        <conditions>
            <not>
                <or>
                    <isUserInRole>ADMIN</isUserInRole>
                    <isUserInRole>ROLE</isUserInRole>
                </or>
            </not>
            <ViewIdMatches>/personal/.*</ViewIdMatches>
        </conditions>
        <actions>
            <jsf-navigation>deny</jsf-navigation>
        </actions>
        <last />
    </rule>
    <rule>
        <conditions>
            <not>
                <isUserInRole>ADMIN</isUserInRole>
            </not>
            <ViewIdMatches>/personal/admin/.*</ViewIdMatches>
        </conditions>
        <actions>
            <jsf-navigation>deny</jsf-navigation>
        </actions>
        <last />
    </rule>-->
</access-config>

=== SalvaFCF/just-another-blog/JAB-WebApp/src/main/webapp/WEB-INF/config/access.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : access.xml
    Created on : September 23, 2008, 1:41 PM
    Author     : sdorra
    Description:
        Purpose of the document follows.
-->
<access-config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                xmlns='http://dev.sonia.de/schema/accessConfig'
                xsi:schemaLocation='http://dev.sonia.de/schema/accessConfig file:///Users/sdorra/Projects/jab/SoniaWebUtil/src/main/resources/sonia/jsf/access/accessConfig.xsd'>

  <rule>
    <description>if app installed</description>
    <conditions>
      <not>
        <uriMatches>/install/.*</uriMatches>
      </not>
      <not>
        <condition>
          <class>sonia.blog.app.InstalledCondition</class>
        </condition>
      </not>
      <uriMatches>.*\.jab</uriMatches>
    </conditions>
    <actions>
      <redirect>/install/step1.jab</redirect>
    </actions>
    <last />
  </rule>

  <rule>
    <conditions>
      <uriMatches>/install/.*</uriMatches>
      <condition>
        <class>sonia.blog.app.InstalledCondition</class>
      </condition>
    </conditions>
    <actions>
      <redirect>/</redirect>
    </actions>
  </rule>

  <rule>
    <conditions>
      <not>
        <scheme>https</scheme>
      </not>
      <uriMatches>(/personal/.*|/login.jab|/register.jab|/lostPassword.jab)</uriMatches>
      <condition>
        <class>sonia.blog.app.ConfigCondition</class>
        <init-param>
          <param-name>key</param-name>
          <param-value>ssl.enable</param-value>
        </init-param>
      </condition>
    </conditions>
    <actions>
      <action>
        <class>sonia.blog.app.SSLRedirectAction</class>
      </action>
    </actions>
  </rule>

  <rule>
    <conditions>
      <or>
        <uriMatches>/personal/.*</uriMatches>
        <uriMatches>/view/reader/.*</uriMatches>
      </or>
      <not>
        <loggedIn />
      </not>
    </conditions>
    <actions>
      <redirect>/error/403.jab</redirect>
    </actions>
    <last />
  </rule>

  <rule>
    <conditions>
      <or>
        <uriMatches>/personal/admin/.*</uriMatches>
        <uriMatches>/view/admin/.*</uriMatches>
      </or>
      <not>
        <or>
          <isUserInRole>ADMIN</isUserInRole>
          <condition>
            <class>sonia.blog.app.GlobalAdminCondition</class>
          </condition>
        </or>
      </not>
    </conditions>
    <actions>
      <redirect>/error/403.jab</redirect>
    </actions>
    <last />
  </rule>

  <rule>
    <conditions>
      <or>
        <uriMatches>/personal/author/.*</uriMatches>
        <uriMatches>/view/author/.*</uriMatches>
      </or>
      <not>
        <or>
          <isUserInRole>AUTHOR</isUserInRole>
          <isUserInRole>ADMIN</isUserInRole>
          <condition>
            <class>sonia.blog.app.GlobalAdminCondition</class>
          </condition>
        </or>
      </not>
    </conditions>
    <actions>
      <redirect>/error/403.jab</redirect>
    </actions>
    <last />
  </rule>

  <rule>
    <conditions>
      <or>
        <uriMatches>/personal/globaladmin/.*</uriMatches>
        <uriMatches>/view/globaladmin/.*</uriMatches>
      </or>
      <not>
        <condition>
          <class>sonia.blog.app.GlobalAdminCondition</class>
        </condition>
      </not>
    </conditions>
    <actions>
      <redirect>/error/403.jab</redirect>
    </actions>
    <last />
  </rule>

  <rule>
    <conditions>
      <uriMatches>.*\.xhtml</uriMatches>
    </conditions>
    <actions>
      <redirect>/error/403.jab</redirect>
    </actions>
  </rule>

</access-config>

=== SalvaFCF/just-another-blog/JAB/src/main/webapp/WEB-INF/config/access.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : access.xml
    Created on : September 23, 2008, 1:41 PM
    Author     : sdorra
    Description:
        Purpose of the document follows.
-->
<access-config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://dev.sonia.de/schema/accessConfig'
   xsi:schemaLocation='http://dev.sonia.de/schema/accessConfig file:/Users/sdorra/Projects/jab/SoniaWebUtil/src/sonia/jsf/access/accessConfig.xsd'>
     
  <rule>
    <description>if app installed</description>
    <conditions>
      <not>
        <ViewIdMatches>/install/.*</ViewIdMatches>
      </not>
      <not>
        <condition>
          <class>sonia.blog.app.InstalledCondition</class>
        </condition>
      </not>
    </conditions>
    <actions>
      <jsf-navigation>install</jsf-navigation>
      <jsf-message>Die Anwendung muss erst installiert werden</jsf-message>
    </actions>
    <last />
  </rule>
  
  <rule>
    <conditions>
      <ViewIdMatches>/install/.*</ViewIdMatches>
      <condition>
        <class>sonia.blog.app.InstalledCondition</class>
      </condition>
    </conditions>
    <actions>
      <redirect>/</redirect>
    </actions>
  </rule>

  <rule>
    <conditions>
      <not>
        <scheme>https</scheme>
      </not>
      <ViewIdMatches>(/personal/.*|/login.xhtml|/register.xhtml|/lostPassword.xhtml)</ViewIdMatches>
      <condition>
        <class>sonia.blog.app.ConfigCondition</class>
        <init-param>
          <param-name>key</param-name>
          <param-value>ssl.enable</param-value>
        </init-param>
      </condition>
    </conditions>
    <actions>
      <action>
        <class>sonia.blog.app.SSLRedirectAction</class>
      </action>
    </actions>
  </rule>

  <rule>
    <conditions>
      <or>
        <ViewIdMatches>/personal/.*</ViewIdMatches>
        <ViewIdMatches>/view/reader/.*</ViewIdMatches>
      </or>
      <not>
        <loggedIn />
      </not>

    </conditions>
    <actions>
      <redirect>/deny.jab</redirect>
    </actions>
    <last />
  </rule>
  
  <rule>
    <conditions>
      <or>
        <ViewIdMatches>/personal/admin/.*</ViewIdMatches>
        <ViewIdMatches>/view/admin/.*</ViewIdMatches>
      </or>
      <not>
        <or>
          <isUserInRole>ADMIN</isUserInRole>
          <condition>
            <class>sonia.blog.app.GlobalAdminCondition</class>
          </condition>
        </or>
      </not>
    </conditions>
    <actions>
      <redirect>/deny.jab</redirect>
    </actions>
    <last />
  </rule>

  <rule>
    <conditions>
      <or>
        <ViewIdMatches>/personal/author/.*</ViewIdMatches>
        <ViewIdMatches>/view/author/.*</ViewIdMatches>
      </or>
      <not>
        <or>
          <isUserInRole>AUTHOR</isUserInRole>
          <isUserInRole>ADMIN</isUserInRole>
          <condition>
            <class>sonia.blog.app.GlobalAdminCondition</class>
          </condition>
        </or>
      </not>
    </conditions>
    <actions>
      <redirect>/deny.jab</redirect>
    </actions>
    <last />
  </rule>

  <rule>
    <conditions>
      <or>
        <ViewIdMatches>/personal/globaladmin/.*</ViewIdMatches>
        <ViewIdMatches>/view/globaladmin/.*</ViewIdMatches>
      </or>
      <not>
        <condition>
          <class>sonia.blog.app.GlobalAdminCondition</class>
        </condition>
      </not>
    </conditions>
    <actions>
      <redirect>/deny.jab</redirect>
    </actions>
    <last />
  </rule>

</access-config>
